---

- name: "install unbound as a local DNSSEC-validating resolver"
  hosts: "all"
  sudo: True
  gather_facts: True

  roles:
    - role: "unbound"
      tags: ["unbound"]


- name: "install postgres for use with discourse"
  hosts: "postgres"
  sudo: True
  gather_facts: True

  roles:
    - role: "postgres-discourse"
      tags: ["postgres-discourse"]


- name: "install and configure redis"
  hosts: "redis"
  sudo: True
  gather_facts: True

  roles:
    - role: "redis"
      tags: ["redis"]


- name: "install discourse, unicorn and nginx"
  hosts: "discourse"
  sudo: True
  gather_facts: True

  roles:
    - role: "discourse"
      tags: ["discourse"]

    - role: "caddy"
